SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;


INSERT INTO `payment_method` (`method_id`, `method_short`, `transaction_fee`, `transaction_percentage`, `paid_by`, `active`) VALUES
(1, 'Check', 0.00, 0.000, 'none', 1),
(2, 'PayPal', 0.30, 2.900, 'payee', 1),
(3, 'Bill Pay', 0.50, 2.500, 'payer', 1),
(4, 'ACH', 0.30, 3.000, 'payer', 1);

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
